[project]
name = "python-fastapi-get-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.125.0",
    "mangum>=0.19.0",
    "pydantic>=2.12.5",
]
